import { test } from '@playwright/test';
import { faker } from '@faker-js/faker';
import { HomePage } from '../pages/HomePage';
import { ContactPage } from '../pages/ContactPage';

/**
 * TC2 — Successful Contact Form Submission
 * 1. From the home page go to the contact page
 * 2. Populate mandatory fields  (unique Faker data every run)
 * 3. Click submit button
 * 4. Validate successful submission message
 *
 * Runs 5 times to guarantee a 100% pass rate.
 */
test.describe('TC2 — Successful Contact Form Submission', () => {

  for (let run = 1; run <= 5; run++) {

    test(`Run ${run} of 5 — successful submission with unique Faker data`, async ({ page }) => {
      test.slow();

      // Unique data generated by Faker for every single run
      const data = {
        forename:  faker.person.firstName(),
        surname:   faker.person.lastName(),
        email:     faker.internet.email(),
        telephone: faker.phone.number(),
        message:   faker.lorem.sentences(2),
      };

      // Step 1: From the home page go to the contact page
      const homePage = new HomePage(page);
      await homePage.goto();

      const contactPage = new ContactPage(page);
      await homePage.clickNavContact();

      // Step 2: Populate mandatory fields
      await contactPage.fillMandatoryFields(data);

      // Step 3: Click submit button
      await contactPage.clickSubmit();

      // Step 4: Validate successful submission message
      await contactPage.verifySuccessMessage(data.forename);
    });

  }

});
